---
# - name: Print all available facts
#   ansible.builtin.debug:
#     var: ansible_facts

# tasks file for dotfiles
- name: Create .zshrc file
  ansible.builtin.template:
    src: templates/zshrc.j2
    dest: "{{ home_user_path }}/.zshrc"

- name: Create .omzrc file
  ansible.builtin.template:
    src: templates/omzrc.j2
    dest: "{{ home_user_path }}/.omzrc"
  when: zsh_framework_config == "ohmyzsh"

- name: Create .ssh/config
  ansible.builtin.template:
    src: templates/ssh-config.j2
    dest: "{{ home_user_path }}/.ssh/config"

- name: Create gitconfig
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: "{{ home_user_path }}/.gitconfig"
