---
# tasks file for dotfiles
- name: Create .zshrc file
  ansible.builtin.template:
    src: templates/zshrc.j2
    dest: "{{ home_user_path }}/.zshrc"
  become: true
  become_user: "{{ ansible_facts['env']['SUDO_USER'] }}"

- name: Create .omzrc file
  ansible.builtin.template:
    src: templates/omzrc.j2
    dest: "{{ home_user_path }}/.omzrc"
  when: zsh_framework_config == "ohmyzsh"
  become: true
  become_user: "{{ ansible_facts['env']['SUDO_USER'] }}"

- name: Create .ssh directory
  ansible.builtin.file:
    state: directory
    path: "{{ home_user_path }}/.ssh"
    mode: '0755'
  become: true
  become_user: "{{ ansible_facts['env']['SUDO_USER'] }}"

- name: Create .ssh/config
  ansible.builtin.template:
    src: templates/ssh-config.j2
    dest: "{{ home_user_path }}/.ssh/config"
  become: true
  become_user: "{{ ansible_facts['env']['SUDO_USER'] }}"

- name: Create gitconfig
  ansible.builtin.template:
    src: templates/gitconfig.j2
    dest: "{{ home_user_path }}/.gitconfig"
  become: true
  become_user: "{{ ansible_facts['env']['SUDO_USER'] }}"

- name: Install neovim config files
  ansible.builtin.copy:
    src: files/nvim
    dest: "{{ home_user_path }}/.config"
