# Shell variables
# Generated by 'wal'
wallpaper='/home/kartik/Pictures/witcher_3.jpg'

# Special
background='#0e1b2b'
foreground='#cebfc1'
cursor='#cebfc1'

# Colors
color0='#0e1b2b'
color1='#C97453'
color2='#DDA16F'
color3='#24708B'
color4='#647489'
color5='#947988'
color6='#358CA1'
color7='#cebfc1'
color8='#908587'
color9='#C97453'
color10='#DDA16F'
color11='#24708B'
color12='#647489'
color13='#947988'
color14='#358CA1'
color15='#cebfc1'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"
